In [1]:
#what I gonna use

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('seaborn-talk')

C:\Users\EDS\AppData\Local\Temp\ipykernel_33764\125052010.py:6: MatplotlibDeprecationWarning: The seaborn styles shipped by Matplotlib are deprecated since 3.6, as they no longer correspond to the styles shipped by seaborn. However, they will remain available as 'seaborn-v0_8-<style>'. Alternatively, directly use the seaborn API instead.
  plt.style.use('seaborn-talk')

In [5]:
data = pd.read_csv('C:\\Users\\EDS\\OneDrive - Extreme Digital Solutions\\Documentos\\TADS020\\Data Science\\Dados-Pesquisa.csv')

C:\Users\EDS\AppData\Local\Temp\ipykernel_33764\2432410912.py:1: DtypeWarning: Columns (21,57) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('C:\\Users\\EDS\\OneDrive - Extreme Digital Solutions\\Documentos\\TADS020\\Data Science\\Dados-Pesquisa.csv')

In [6]:
data.head(1-2)

,Age,AttendedBootcamp,BootcampFinish,BootcampFullJobAfter,BootcampLoanYesNo,BootcampMonthsAgo,BootcampName,BootcampPostSalary,BootcampRecommend,ChildrenNumber,...,ResourceSoloLearn,ResourceStackOverflow,ResourceTreehouse,ResourceUdacity,ResourceUdemy,ResourceW3Schools,ResourceYouTube,SchoolDegree,SchoolMajor,StudentDebtOwe
0,28.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"some college credit, no degree",NaN,20000.0
1,22.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,"some college credit, no degree",NaN,NaN
2,19.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,high school diploma or equivalent (GED),NaN,NaN
3,26.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bachelor's degree,Cinematography And Film,7000.0
4,20.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"some college credit, no degree",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15614,47.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"trade, technical, or vocational training",NaN,NaN
15615,39.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,bachelor's degree,Chemistry,NaN
15616,27.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,bachelor's degree,Electrical Engineering,NaN
15617,37.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bachelor's degree,Chemistry,NaN
15618,26.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,master's degree (non-professional),Math,NaN

In [8]:
data.columns.to_list()

['Age',
 'AttendedBootcamp',
 'BootcampFinish',
 'BootcampFullJobAfter',
 'BootcampLoanYesNo',
 'BootcampMonthsAgo',
 'BootcampName',
 'BootcampPostSalary',
 'BootcampRecommend',
 'ChildrenNumber',
 'CityPopulation',
 'CodeEventBootcamp',
 'CodeEventCoffee',
 'CodeEventConferences',
 'CodeEventDjangoGirls',
 'CodeEventGameJam',
 'CodeEventGirlDev',
 'CodeEventHackathons',
 'CodeEventMeetup',
 'CodeEventNodeSchool',
 'CodeEventNone',
 'CodeEventOther',
 'CodeEventRailsBridge',
 'CodeEventRailsGirls',
 'CodeEventStartUpWknd',
 'CodeEventWomenCode',
 'CodeEventWorkshop',
 'CommuteTime',
 'CountryCitizen',
 'CountryLive',
 'EmploymentField',
 'EmploymentFieldOther',
 'EmploymentStatus',
 'EmploymentStatusOther',
 'ExpectedEarning',
 'FinanciallySupporting',
 'Gender',
 'HasChildren',
 'HasDebt',
 'HasFinancialDependents',
 'HasHighSpdInternet',
 'HasHomeMortgage',
 'HasServedInMilitary',
 'HasStudentDebt',
 'HomeMortgageOwe',
 'HoursLearning',
 'ID.x',
 'ID.y',
 'Income',
 'IsEthnicMinority',
 'IsReceiveDiabilitiesBenefits',
 'IsSoftwareDev',
 'IsUnderEmployed',
 'JobApplyWhen',
 'JobPref',
 'JobRelocateYesNo',
 'JobRoleInterest',
 'JobRoleInterestOther',
 'JobWherePref',
 'LanguageAtHome',
 'MaritalStatus',
 'MoneyForLearning',
 'MonthsProgramming',
 'NetworkID',
 'Part1EndTime',
 'Part1StartTime',
 'Part2EndTime',
 'Part2StartTime',
 'PodcastChangeLog',
 'PodcastCodeNewbie',
 'PodcastCodingBlocks',
 'PodcastDeveloperTea',
 'PodcastDotNetRocks',
 'PodcastHanselminutes',
 'PodcastJSJabber',
 'PodcastJsAir',
 'PodcastNone',
 'PodcastOther',
 'PodcastProgrammingThrowDown',
 'PodcastRubyRogues',
 'PodcastSEDaily',
 'PodcastShopTalk',
 'PodcastTalkPython',
 'PodcastWebAhead',
 'ResourceBlogs',
 'ResourceBooks',
 'ResourceCodeWars',
 'ResourceCodecademy',
 'ResourceCoursera',
 'ResourceDevTips',
 'ResourceEdX',
 'ResourceEggHead',
 'ResourceFCC',
 'ResourceGoogle',
 'ResourceHackerRank',
 'ResourceKhanAcademy',
 'ResourceLynda',
 'ResourceMDN',
 'ResourceOdinProj',
 'ResourceOther',
 'ResourcePluralSight',
 'ResourceReddit',
 'ResourceSkillCrush',
 'ResourceSoloLearn',
 'ResourceStackOverflow',
 'ResourceTreehouse',
 'ResourceUdacity',
 'ResourceUdemy',
 'ResourceW3Schools',
 'ResourceYouTube',
 'SchoolDegree',
 'SchoolMajor',
 'StudentDebtOwe']

In [9]:
df2 = data.copy()

In [10]:
df2.isna().sum()

Age                      2007
AttendedBootcamp          240
BootcampFinish          14687
BootcampFullJobAfter    14985
BootcampLoanYesNo       14686
                        ...
ResourceW3Schools       15499
ResourceYouTube         15499
SchoolDegree             1941
SchoolMajor              7170
StudentDebtOwe          12106
Length: 113, dtype: int64

In [12]:
df2.isna().sum().sum()

1183948

In [13]:
df2.dropna(subset = ['Age'], inplace = True)

In [14]:
df2.isna().mean()

Age                     0.000000
AttendedBootcamp        0.008227
BootcampFinish          0.940939
BootcampFullJobAfter    0.959965
BootcampLoanYesNo       0.940645
                          ...
ResourceW3Schools       0.992287
ResourceYouTube         0.992140
SchoolDegree            0.008301
SchoolMajor             0.386763
StudentDebtOwe          0.743480
Length: 113, dtype: float64